### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mohammad-aqajani** [misli/django-verified-email-field#1]
hi I'm a newbie would you help me with this error: 
    url(r'^verified-email-field/',include (verified_email_field.urls, 'verified-email-field', 'verified-email-field')),
NameError: name 'verified_email_field' is not defined

**Comment by misli** [comment]
Thank You for this question.
You need to import `verified_email_field` Your in `urls.py`:
```python
import verified_email_field
```
I'll update the example in README.
