### ISSUE TITLE
send.js ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by johngebbie** [misli/django-verified-email-field#10]
Hi. I have put {{ form.media.js }} in the head of the template but I keep getting this error.
`ReferenceError: $ is not defined
    send_verification_code http://localhost:8000/static/verified_email_field/send.js:19
    onclick http://localhost:8000/register/:1`

I don't know jQuery but I know it uses the $. Is that maybe what this is about, I am not using it, or am I missing something?

Thanks.
I am using Firefox 67.

**Comment by misli** [comment]
Yep, it needs [jQuery](https://code.jquery.com/) to work properly. It is so simple, that it should work with any version.

**Comment by misli** [comment]
In fact, it is so simple that is could be implemented even without jQuery, but I don't have much experience with JS support in different browsers. Any PR is welcome.

**Comment by misli** [comment]
This is fixed in version 1.8 thanks to @sumanthratna .
