### ISSUE TITLE
example

### ISSUE THREAD

**Issue by mohammad-aqajani** [misli/django-verified-email-field#2]
import verified-email-field.urls too

and would you write template example , please!
doesn't seem to send email!
thanks.

**Comment by misli** [comment]
`verified_email` uses [django.core.mail](https://docs.djangoproject.com/en/dev/topics/email/) to send emails.
Generally, if you want your django site to send emails, you need either some local mail server (sendmail for example) running on your host or configure your site to use some remote SMTP server.
To configure your site to use SMTP server, add [`EMAIL_HOST`](https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-EMAIL_HOST) to your `settings.py`. (You may also need some other settings like [`EMAIL_HOST_USER`](https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-EMAIL_HOST_USER) and [`EMAIL_HOST_PASSWORD`](https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-EMAIL_HOST_PASSWORD).)

**Comment by misli** [comment]
It also doesn't work yet with Django 1.11. (see  #6)
