### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by hemangr8** [misli/django-verified-email-field#3]
I am getting the error "Unresolved reference verified_email_field" in the settings.INSTALLED_APPS even after installing django-verified-email-field using pip.

**Comment by misli** [comment]
Hi,
could You please provide more details? I can't find, where could such message come from.

**Comment by misli** [comment]
Looking at the results of google search "python unresolved reference", I assume that it is something You get from PyCharm. Unfortunately, I don't use PyCharm, so I'm not able to help You with the setup.
